var keyMirror = require("keymirror");

module.exports = keyMirror({
  SELECT_PROFILE: null,
  SELECT_MODEL: null,
  SELECT_DATA_SET: null,
  SELECT_FEATURE: null,
  SELECT_ALIGNMENT: null,
  SELECT_TRAJECTORY: null,
  SELECT_PHASE: null,

  CHANGE_SHOW_PHASE_OVERLAY: null,
  CHANGE_PHASE_OVERLAY_OPACITY: null,

  RUN_SIMULATION: null,
  CHANGE_SIMULATION_PARAMETER: null,
  CHANGE_SPECIES_INITIAL_VALUE: null,
  CHANGE_SPECIES_PHASE_INTERACTION: null,
  CHANGE_SPECIES_SPECIES_INTERACTION: null,

  RECEIVE_PROFILE_LIST: null,
  RECEIVE_DATA_SET_LIST: null,
  RECEIVE_PROFILE: null,
  RECEIVE_DATA_SET: null,
  RECEIVE_SIMULATION_OUTPUT: null,

  SIMULATION_OUTPUT_NONE: null,
  SIMULATION_OUTPUT_WAITING: null,
  SIMULATION_OUTPUT_INVALID: null,
  SIMULATION_OUTPUT_VALID: null
});
