postgis:
  image: mjstealey/hs_postgres:9.4.7
  container_name: postgis
rabbitmq:
  image: rabbitmq:3.5
  container_name: rabbitmq
cellcycle:
  build: .
  container_name: cellcycle
  cap_add:
    - SYS_ADMIN
  privileged: true
  environment:
    POSTGIS_HOST: postgis
    POSTGIS_PORT: 5432
    POSTGIS_PASSWORD: postgres
    POSTGIS_DB: postgres
    POSTGIS_USER: postgres
    PGPASSWORD: postgres
  volumes:
    # cellcycle repository
    - "/home/ccbuild/CellCycleBrowser:/home/docker/cellcycle"
    # log files
    - "/home/ccbuild/CellCycleBrowser/log:/var/log/cellcycle"
    # shared location for uwsgi.sock between containers
    - "/var/run"
    # temp directory shared with celery workers
    - "/shared_temp"
  ports:
    - "1338:22"
    - "8000:8000"
  links:
    - postgis:postgis
    - rabbitmq:rabbitmq
  command: /bin/bash init
defaultworker:
  build: .
  container_name: defaultworker
  environment:
    POSTGIS_HOST: postgis
    POSTGIS_PORT: 5432
    POSTGIS_PASSWORD: postgres
    POSTGIS_DB: postgres
    PGPASSWORD: postgres
    C_FORCE_ROOT: 1
  volumes_from:
    - cellcycle
  volumes:
    - "/var/run/docker.sock:/docker.sock"
  links:
    - postgis:postgis
    - rabbitmq:rabbitmq
  command: ./run_celery.sh
