# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 21:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cc_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_filename', models.CharField(max_length=100)),
                ('metadata_dict', django.contrib.postgres.fields.hstore.HStoreField(default={})),
            ],
        ),
    ]
