apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: cellcyclebrowser
data:
  {{ range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{ end }}
  update-site.sql: |
    UPDATE django_site SET name = '{{ .Values.initDbJob.siteDomain }}', domain = '{{ .Values.initDbJob.siteDomain }}' WHERE id = 1;
