apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: cellcyclebrowser-postgres
spec:
  serviceName: {{ .Release.Name }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: cellcyclebrowser-postgres
  template:
    metadata:
      labels:
        app: cellcyclebrowser-postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        ports:
        - containerPort: {{ .Values.postgres.port }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        - name: POSTGRES_HOST_AUTH_METHOD
          value: {{ .Values.postgres.authMethod }}  
        resources:
          {{ toYaml .Values.postgres.resources | nindent 10 }}
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: {{ .Values.postgres.storage.storageClass }}
      resources:
        requests:
          storage: {{ .Values.postgres.storage.size }}
