apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: cellcyclebrowser-postgres
spec:
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
    protocol: TCP
  selector:
    app: cellcyclebrowser-postgres
  clusterIP: None
