apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    app: cellcyclebrowser-rabbitmq
spec:
  serviceName: {{ .Release.Name }}-rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: cellcyclebrowser-rabbitmq
  template:
    metadata:
      labels:
        app: cellcyclebrowser-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image }}
        ports:
        - containerPort: {{ .Values.rabbitmq.port }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmq.user }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitmq.password }}
        resources:
          {{ toYaml .Values.rabbitmq.resources | nindent 10 }}
