apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    app: cellcyclebrowser-rabbitmq
spec:
  ports:
  - port: {{ .Values.rabbitmq.port }}
    targetPort: {{ .Values.rabbitmq.port }}
    protocol: TCP
  selector:
    app: cellcyclebrowser-rabbitmq
  clusterIP: None
