apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: cellcyclebrowser-redis
spec:
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
    protocol: TCP
    name: redis
  selector:
    app: cellcyclebrowser-redis
  clusterIP: None
