apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
