apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django
  labels:
    app: cellcyclebrowser-django
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    app: cellcyclebrowser-django
  type: {{ .Values.service.type }}
