### Hostname ###
FQDN_OR_IP: localhost

### Application configuration ###
CC_PATH: /home/ccbuild/CellCycleBrowser/server
CC_DATABASE: cellcycle_db.sql
CC_MEDIA_FILES: media.cc-testing.tar.gz
HOST_USER_UID: 1000
HOST_USER_GID: 1000
### Nginx configuration ###
USE_NGINX: false
NGINX_DIR: nginx
NGINX_CONF_FILE: cc-nginx.conf

### REQUIRES BLANK LINE AFTER LAST VARIABLE DEFINITION ###
