cc-db:
  image: postgres:9.4
  container_name: cc-db
cc-redis:
  image: redis:2.8
  container_name: cc-redis
cc-rabbitmq:
  image: rabbitmq:3.5
  container_name: cc-rabbitmq
cellcycle:
  build: .
  container_name: cellcycle
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
    REDIS_HOST: redis
    REDIS_PORT: 6379
  volumes:
    # cellcycle repository
    - "CC_PATH:/home/docker/cellcycle"
    - "CC_PATH/Stochpy:/home/docker/Stochpy"
    # log files
    - "CC_PATH/log:/home/docker/cellcycle/log"
    # - "/home/hongyi/pycharm-debug:/home/docker/pycharm-debug"
    # shared location for uwsgi.sock between containers
    - "/var/run"
    # temp directory shared with celery workers
    - "/shared_temp"
  ports:
    - "1338:22"
    - "8000:8000"
  links:
    - cc-db:cc-db
    - cc-redis:cc-redis
    - cc-rabbitmq:cc-rabbitmq
  command: /bin/bash init
cc-defaultworker:
  build: .
  container_name: cc-defaultworker
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
    REDIS_HOST: redis
    REDIS_PORT: 6379
  volumes_from:
    - cellcycle
  volumes:
    - "/var/run/docker.sock:/docker.sock"
  links:
    - cc-db:cc-db
    - cc-redis:cc-redis
    - cc-rabbitmq:cc-rabbitmq
  command: /bin/bash init-defaultworker
