db:
  image: postgres:9.4
  container_name: cc-db
redis:
  image: redis:2.8
  container_name: cc-redis
rabbitmq:
  image: rabbitmq:3.5
  container_name: cc-rabbitmq
cellcycle:
  build: .
  container_name: cellcycle
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
    REDIS_HOST: redis
    REDIS_PORT: 6379
  volumes:
    # cellcycle repository
    - "/home/ccbuild/CellCycleBrowser/server:/home/docker/cellcycle"
    - "/home/ccbuild/CellCycleBrowser/server/Stochpy:/home/docker/Stochpy"
    # log files
    - "/home/ccbuild/CellCycleBrowser/server/log:/home/docker/cellcycle/log"
    # shared location for uwsgi.sock between containers
    - "/var/run"
    # temp directory shared with celery workers
    - "/shared_temp"
  ports:
    - "1338:22"
    - "8000:8000"
  links:
    - db:db
    - redis:redis
    - rabbitmq:rabbitmq
  command: /bin/bash init
defaultworker:
  build: .
  container_name: cc-defaultworker
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
    REDIS_HOST: redis
    REDIS_PORT: 6379
    C_FORCE_ROOT: 1
  volumes_from:
    - cellcycle
  volumes:
    - "/var/run/docker.sock:/docker.sock"
  links:
    - db:db
    - redis:redis
    - rabbitmq:rabbitmq
  command: /bin/bash init-defaultworker
nginx:
  container_name: cc-nginx
  image: nginx:1.9
  volumes_from:
    - cellcycle
  ports:
    - "80:80"
    - "443:443"
  links:
    - cellcycle:cellcycle
